# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CoreDataDemo' do
pod 'MagicalRecord'
pod 'AFNetworking'
pod 'Mantle'
pod 'libextobjc'
end

target 'CoreDataDemoTests' do

end

target 'CoreDataDemoUITests' do

end

